export enum PetsActionType {
    REQUEST_PETS = 'REQUEST_PETS',
    RECEIVE_PETS = 'RECEIVE_PETS',
    FETCH_PETS_ERROR = 'FETCH_PETS_ERROR',
    POST_REQUEST = 'POST_REQUEST',
    POST_RECEIVE = 'POST_RECEIVE',
    POST_ERROR = 'POST_ERROR',
}
