import { checkSession, logout, signIn, signUp } from './Login/action';
import { deleteAnimal, getAnimals, postAnimal } from './Pets/actions';
import { getTherapiesList } from './Therapy/actions/getTherapiesList';
import { getToday } from './Today/actions/getToday';
import { createToday } from './Today/actions/createToday';
import { deleteToday } from './Today/actions/deleteToday';
export const CheckSession = checkSession;
export const GetAnimals = getAnimals;
export const PostAnimal = postAnimal;
export const GetToday = getToday;
export const GetTherapies = getTherapiesList;
export const CreateToday = createToday;
export const DeleteToday = deleteToday;
export const SignIn = signIn;
export const SignUp = signUp;
export const DeletePet = deleteAnimal;
export const LogOut = logout;
