export enum LoginActionType {
    INIT_SESSION = 'INIT_SESSION',
    INIT_SESSION_SUCCESS = 'INIT_SESSION_SUCCESS',
    INIT_SESSION_ERROR = 'INIT_SESSION_ERROR',
    REQUEST_LOGIN = 'REQUEST_LOGIN',
    RECEIVE_LOGIN = 'RECEIVE_LOGIN',
    FETCH_LOGIN_ERROR = 'FETCH_LOGIN_ERROR',
    REQUSET_SIGNUP = 'REQUEST_SIGNUP',
    RECEIVE_SIGNUP = 'RECEIVE_SIGNUP',
    ERROR_SIGNUP = 'ERROR_SIGNUP',
    LOGOUT = 'LOGOUT',
}
