export enum TodayActionTypes {
    REQUEST_TODAY = 'REQUEST_TODAY',
    RECEIVE_TODAY = 'RECEIVE_TODAY',
    FETCH_TODAY_ERROR = 'FETCH_TODAY_ERROR',
    REQUEST_CREATE_TODAY = 'REQUEST_CREATE_TODAY',
    RECEIVE_CREATE_TODAY = 'RECEIVE_CREATE_TODAY',
    FETCH_CREATE_TODAY_ERROR = 'FETCH_CREATE_TODAY_ERROR',
}
